import type { NextApiRequest, NextApiResponse } from 'next';
import axios from 'axios';
import { Groq } from 'groq-sdk';

// Initialize Groq client
function getGroqClient() {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) {
    throw new Error('GROQ_API_KEY is required. Add it in Vercel environment variables.');
  }
  return new Groq({ apiKey });
}

// Improved JSON parsing with error handling
function safeParseJSON(content: string) {
  console.log('🔄 Attempting to parse JSON, length:', content.length);
  
  let cleaned = content.trim();
  
  // Remove markdown code blocks
  if (cleaned.startsWith('```json')) cleaned = cleaned.substring(7);
  if (cleaned.startsWith('```')) cleaned = cleaned.substring(3);
  if (cleaned.endsWith('```')) cleaned = cleaned.substring(0, cleaned.length - 3);
  
  // Extract JSON between first { and last }
  const jsonStart = cleaned.indexOf('{');
  const jsonEnd = cleaned.lastIndexOf('}') + 1;
  
  if (jsonStart !== -1 && jsonEnd > jsonStart) {
    cleaned = cleaned.substring(jsonStart, jsonEnd);
  }
  
  try {
    const parsed = JSON.parse(cleaned);
    console.log('✅ JSON parsed successfully');
    return parsed;
  } catch (parseError: any) {
    console.error('❌ JSON parse error:', parseError.message);
    
    // Try to fix common issues
    try {
      const fixed = cleaned
        .replace(/,\s*}/g, '}')
        .replace(/,\s*]/g, ']')
        .replace(/'/g, '"')
        .replace(/:\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*([,}])/g, ':"$1"$2');
      
      const reparsed = JSON.parse(fixed);
      console.log('✅ JSON re-parsed after fixing');
      return reparsed;
    } catch (e) {
      console.error('❌ Still cannot parse JSON, using fallback');
      return getFallbackResponse(cleaned.substring(0, 100));
    }
  }
}

function getFallbackResponse(queryHint: string) {
  return {
    playerInfo: null,
    teamInfo: null,
    worldCupInfo: null,
    analysis: "Analysis generated by AI",
    videoSearchTerm: "football highlights 2024",
    confidenceScore: 0.5
  };
}

// Generate current date string for prompt
function getCurrentDateContext() {
  const now = new Date();
  const month = now.toLocaleString('en-US', { month: 'long' });
  const year = now.getFullYear();
  return `${month} ${year}`;
}

// SIMPLIFIED and more reliable prompt
async function analyzeFootballQuery(query: string) {
  console.log('🤖 Starting AI analysis for:', query);
  const groq = getGroqClient();
  
  const currentDate = getCurrentDateContext();
  
  // Determine query type for the prompt
  const queryLower = query.toLowerCase();
  let queryTypeHint = '';
  
  if (queryLower.includes('world cup')) {
    queryTypeHint = 'WORLD CUP - Use format 4';
  } else if (
    queryLower.includes('national team') ||
    ['spain', 'brazil', 'argentina', 'france', 'germany', 'italy', 'england', 'portugal', 'netherlands', 'belgium'].some(country => queryLower.includes(country))
  ) {
    queryTypeHint = 'NATIONAL TEAM - Use format 3';
  } else if (
    queryLower.includes('real madrid') || queryLower.includes('barcelona') || 
    queryLower.includes('manchester') || queryLower.includes('bayern') ||
    queryLower.includes('psg') || queryLower.includes('juventus') ||
    queryLower.includes('chelsea') || queryLower.includes('arsenal') ||
    queryLower.includes('liverpool') || queryLower.includes('ac milan') ||
    queryLower.includes('inter milan')
  ) {
    queryTypeHint = 'CLUB TEAM - Use format 2';
  } else {
    queryTypeHint = 'PLAYER - Use format 1';
  }
  
  const prompt = `You are FutbolAI, an expert football analyst with data up to ${currentDate}.

Analyze this query: "${query}"

${queryTypeHint}

Return ONLY valid JSON in one of these exact formats:

FORMAT 1 - FOR PLAYERS:
{
  "playerInfo": {
    "name": "Full name",
    "position": "Primary position",
    "nationality": "Country",
    "currentClub": "Current club",
    "age": "Current age",
    "height": "Height in cm",
    "preferredFoot": "Left/Right/Both",
    "marketValue": "Estimated value",
    "careerStats": {
      "club": {"totalGoals": 0, "totalAssists": 0, "totalAppearances": 0},
      "international": {"caps": 0, "goals": 0}
    },
    "achievementsSummary": {
      "worldCupTitles": 0,
      "continentalTitles": 0,
      "clubContinentalTitles": 0,
      "clubDomesticTitles": {"leagues": 0, "cups": 0}
    }
  },
  "teamInfo": null,
  "worldCupInfo": null,
  "analysis": "Brief 100-word analysis focusing on key achievements and current status",
  "videoSearchTerm": "[Player Name] football highlights 2024",
  "confidenceScore": 0.95
}

FORMAT 2 - FOR CLUB TEAMS:
{
  "playerInfo": null,
  "teamInfo": {
    "name": "Full club name",
    "type": "club",
    "founded": "Year",
    "league": "Current league",
    "currentManager": {"name": "Current manager"},
    "stadium": {"name": "Stadium name", "capacity": "Number"},
    "achievementsSummary": {
      "continentalTitles": 0,
      "internationalTitles": 0,
      "domesticTitles": {"leagues": 0, "cups": 0}
    },
    "trophies": {
      "continental": [
        {"competition": "UEFA Champions League", "wins": 0, "icon": "⭐"}
      ],
      "international": [
        {"competition": "FIFA Club World Cup", "wins": 0, "icon": "🌍"}
      ],
      "domestic": {
        "league": [
          {"competition": "La Liga", "wins": 0, "icon": "🥇"}
        ],
        "cup": [
          {"competition": "Copa del Rey", "wins": 0, "icon": "🏆"}
        ]
      }
    }
  },
  "worldCupInfo": null,
  "analysis": "Brief 100-word analysis focusing on trophy history and current season",
  "videoSearchTerm": "[Team Name] football highlights 2024",
  "confidenceScore": 0.95
}

FORMAT 3 - FOR NATIONAL TEAMS:
{
  "playerInfo": null,
  "teamInfo": {
    "name": "Country name",
    "type": "national",
    "fifaRanking": "Current ranking",
    "currentCoach": {"name": "Current coach"},
    "achievementsSummary": {
      "worldCupTitles": 0,
      "continentalTitles": 0
    },
    "majorHonors": [
      {"competition": "FIFA World Cup", "titles": 0, "icon": "🏆"}
    ]
  },
  "worldCupInfo": null,
  "analysis": "Brief 100-word analysis focusing on World Cup and continental achievements",
  "videoSearchTerm": "[Country] national team football 2024",
  "confidenceScore": 0.95
}

FORMAT 4 - FOR WORLD CUP:
{
  "playerInfo": null,
  "teamInfo": null,
  "worldCupInfo": {
    "year": 2026,
    "host": "Host countries",
    "defendingChampion": "Current champion"
  },
  "analysis": "Brief 100-word analysis of the upcoming tournament",
  "videoSearchTerm": "World Cup 2026 football",
  "confidenceScore": 0.95
}

IMPORTANT:
1. Use ONLY the format indicated by the query type
2. Fill in ACCURATE, REAL data
3. For trophies, use exact numbers (e.g., Real Madrid has 14 UCL titles)
4. Return ONLY the JSON, no other text
5. If unsure about a number, use 0`;

  try {
    console.log('🚀 Calling Groq with query:', query);
    console.log('💡 Query type hint:', queryTypeHint);
    
    const completion = await groq.chat.completions.create({
      messages: [{ role: 'user', content: prompt }],
      model: 'llama-3.3-70b-versatile',
      temperature: 0.1,
      max_tokens: 2000,
    });

    const content = completion.choices[0]?.message?.content || '{}';
    console.log('📄 Raw AI response (first 300 chars):', content.substring(0, 300) + '...');
    
    const parsed = safeParseJSON(content);
    console.log('✅ JSON parsed:', {
      hasPlayerInfo: !!parsed.playerInfo,
      hasTeamInfo: !!parsed.teamInfo,
      hasWorldCupInfo: !!parsed.worldCupInfo,
      teamType: parsed.teamInfo?.type,
      analysisLength: parsed.analysis?.length || 0
    });
    
    // Ensure required fields
    if (!parsed.analysis) {
      parsed.analysis = `Analysis of ${query}.`;
    }
    if (!parsed.videoSearchTerm) parsed.videoSearchTerm = `${query} football highlights 2024`;
    if (!parsed.confidenceScore) parsed.confidenceScore = 0.8;
    
    return parsed;
    
  } catch (error: any) {
    console.error('❌ Groq API error:', error.message);
    return getFallbackResponse(query);
  }
}

// Enhanced YouTube search with better error handling
async function searchYouTube(searchTerm: string) {
  console.log('🎬 Searching YouTube for:', searchTerm);
  
  try {
    const apiKey = process.env.YOUTUBE_API_KEY;
    
    if (!apiKey) {
      console.warn('⚠️ YouTube API key not set');
      // Try a public search fallback
      return getPublicYouTubeFallback(searchTerm);
    }

    // Clean and optimize search term
    const cleanTerm = searchTerm
      .replace(/\[.*?\]/g, '') // Remove brackets
      .replace(/\s+/g, ' ')    // Normalize spaces
      .trim();
    
    const query = `${cleanTerm} football 2024`;
    console.log('🔍 Optimized YouTube query:', query);
    
    const response = await axios.get('https://www.googleapis.com/youtube/v3/search', {
      params: {
        part: 'snippet',
        q: query,
        type: 'video',
        maxResults: 3,
        key: apiKey,
        videoEmbeddable: 'true',
        safeSearch: 'none',
        order: 'viewCount',
        videoDuration: 'any',
        relevanceLanguage: 'en',
      },
      timeout: 5000, // 5 second timeout
    });

    console.log('📊 YouTube API response:', {
      status: response.status,
      items: response.data.items?.length || 0
    });
    
    if (response.data.items?.length > 0) {
      // Pick the first result (most viewed)
      const videoId = response.data.items[0].id.videoId;
      const videoUrl = `https://www.youtube.com/embed/${videoId}`;
      console.log('✅ YouTube video found:', videoUrl);
      return videoUrl;
    } else {
      console.warn('📭 No YouTube videos found, using fallback');
      return getPublicYouTubeFallback(searchTerm);
    }
  } catch (error: any) {
    console.error('❌ YouTube search error:', {
      message: error.message,
      code: error.code,
      status: error.response?.status
    });
    
    return getPublicYouTubeFallback(searchTerm);
  }
}

// Public YouTube fallback (no API key needed for specific videos)
function getPublicYouTubeFallback(searchTerm: string) {
  const term = searchTerm.toLowerCase();
  
  // Curated high-quality football highlights
  const publicVideos: Record<string, string> = {
    // Clubs
    'real madrid': 'XfyZ6EueJx8',
    'barcelona': '3X7XG5KZiUY',
    'manchester city': 'KXwHEvDE2-U',
    'liverpool': '6MfLJBHjK0k',
    'bayern': 'HfQmI1Q5LQc',
    'psg': '8CjDcFyF2l0',
    'juventus': 'Uf4nVHLLqPA',
    'ac milan': 'V7GqQN5Dm1k',
    'inter milan': 'dZqkf1ZnQh4',
    'chelsea': 'dZqkf1ZnQh4',
    'arsenal': 'dZqkf1ZnQh4',
    'manchester united': 'dZqkf1ZnQh4',
    
    // National Teams
    'spain': 'eJXWcJeGXlM',
    'brazil': 'eJXWcJeGXlM',
    'argentina': 'eJXWcJeGXlM',
    'france': 'J8LcQOHtQKs',
    'germany': 'dZqkf1ZnQh4',
    'italy': 'dZqkf1ZnQh4',
    'england': 'dZqkf1ZnQh4',
    'portugal': 'dZqkf1ZnQh4',
    'netherlands': 'dZqkf1ZnQh4',
    'belgium': 'dZqkf1ZnQh4',
    'colombia': 'dZqkf1ZnQh4',
    
    // Players
    'ronaldo': 'OUKGsb8CpF8',
    'messi': 'ZO0d8r_2qGI',
    'mbappe': 'RdGpDPLT5Q4',
    'haaland': '4XqQpQ8KZg4',
    'neymar': 'FIYzK8PSLpA',
    'benzema': '6kl7AOKVpCM',
    'modric': 'dZqkf1ZnQh4',
    'kroos': 'dZqkf1ZnQh4',
    'vinicius': 'dZqkf1ZnQh4',
    'bellingham': 'dZqkf1ZnQh4',
    
    // World Cup
    'world cup': 'dZqkf1ZnQh4',
  };

  for (const [key, videoId] of Object.entries(publicVideos)) {
    if (term.includes(key)) {
      console.log('🔄 Using public fallback for:', key);
      return `https://www.youtube.com/embed/${videoId}`;
    }
  }

  // Default to a popular football highlights channel
  console.log('🔄 Using default football highlights');
  return 'https://www.youtube.com/embed/dZqkf1ZnQh4';
}

// Main API handler
export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader('Access-Control-Allow-Headers', 'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version');

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  const { action, query } = req.query;

  if (action === 'search' && query && typeof query === 'string') {
    console.log(`\n=== NEW REQUEST: "${query}" ===`);
    
    try {
      // Try AI analysis
      const aiAnalysis = await analyzeFootballQuery(query);
      
      // Determine the type based on what data we have
      let responseType = 'general';
      if (aiAnalysis.playerInfo) {
        responseType = 'player';
      } else if (aiAnalysis.teamInfo) {
        responseType = aiAnalysis.teamInfo.type === 'national' ? 'national' : 'club';
      } else if (aiAnalysis.worldCupInfo) {
        responseType = 'worldCup';
      }
      
      console.log('✅ AI Analysis completed, type:', responseType);
      console.log('📊 Data structure:', {
        playerInfo: !!aiAnalysis.playerInfo,
        teamInfo: !!aiAnalysis.teamInfo,
        worldCupInfo: !!aiAnalysis.worldCupInfo,
        teamType: aiAnalysis.teamInfo?.type
      });
      
      const searchTerm = aiAnalysis.videoSearchTerm || query;
      console.log('🎯 YouTube search term:', searchTerm);
      
      const youtubeUrl = await searchYouTube(searchTerm);
      console.log('✅ Final YouTube URL:', youtubeUrl);
      
      const response = {
        success: true,
        query: query,
        timestamp: new Date().toISOString(),
        type: responseType,
        data: aiAnalysis.playerInfo || aiAnalysis.teamInfo || aiAnalysis.worldCupInfo || null,
        playerInfo: aiAnalysis.playerInfo || null,
        teamInfo: aiAnalysis.teamInfo || null,
        worldCupInfo: aiAnalysis.worldCupInfo || null,
        youtubeUrl: youtubeUrl,
        analysis: aiAnalysis.analysis || `Comprehensive analysis of ${query}`,
        confidence: aiAnalysis.confidenceScore || 0.8,
        source: 'Groq AI',
        debug: 'AI_SUCCESS'
      };

      return res.status(200).json(response);
      
    } catch (error: any) {
      console.error('❌ API error:', error.message);
      
      return res.status(200).json({
        success: false,
        query: query,
        type: 'error',
        error: 'Service temporarily unavailable',
        timestamp: new Date().toISOString(),
        youtubeUrl: getPublicYouTubeFallback(query),
        analysis: `Please try your search again in a moment.`,
        debug: 'SERVICE_ERROR'
      });
    }
  }

  // API docs
  res.status(200).json({
    message: 'FutbolAI Enhanced API is running! 🏆',
    version: '3.0',
    features: 'Detailed football analytics with trophy counts, current managers, and enhanced data',
    endpoints: {
      search: 'GET /api/ai?action=search&query=your-query',
      examples: [
        '/api/ai?action=search&query=Real%20Madrid',
        '/api/ai?action=search&query=Spain%20national%20team',
        '/api/ai?action=search&query=Cristiano%20Ronaldo',
        '/api/ai?action=search&query=World%20Cup%202026'
      ]
    }
  });
}