import type { NextApiRequest, NextApiResponse } from 'next';
import axios from 'axios';
import { Groq } from 'groq-sdk';

// Initialize Groq client
function getGroqClient() {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) {
    throw new Error('GROQ_API_KEY is required. Add it in Vercel environment variables.');
  }
  return new Groq({ apiKey });
}

// Simple JSON parsing
function safeParseJSON(content: string) {
  try {
    // Try to extract JSON from the response
    let cleaned = content.trim();
    
    // Remove markdown code blocks
    if (cleaned.startsWith('```json')) cleaned = cleaned.substring(7);
    if (cleaned.startsWith('```')) cleaned = cleaned.substring(3);
    if (cleaned.endsWith('```')) cleaned = cleaned.substring(0, cleaned.length - 3);
    
    // Find first { and last }
    const jsonStart = cleaned.indexOf('{');
    const jsonEnd = cleaned.lastIndexOf('}') + 1;
    
    if (jsonStart !== -1 && jsonEnd > jsonStart) {
      cleaned = cleaned.substring(jsonStart, jsonEnd);
    }
    
    return JSON.parse(cleaned);
  } catch (error) {
    console.error('JSON parse error, returning fallback');
    return {
      playerInfo: null,
      teamInfo: null,
      worldCupInfo: null,
      analysis: "Analysis generated by AI",
      videoSearchTerm: "football highlights",
      confidenceScore: 0.5
    };
  }
}

// SIMPLE, RELIABLE PROMPT
async function analyzeFootballQuery(query: string) {
  console.log('🤖 Analyzing:', query);
  const groq = getGroqClient();
  
  const prompt = `You are a football expert. Analyze: "${query}"

Return ONLY valid JSON in this exact structure:

{
  "playerInfo": null OR {
    "name": "Player name",
    "position": "Position",
    "nationality": "Country",
    "currentClub": "Current club",
    "age": "Age",
    "achievementsSummary": {
      "worldCupTitles": 0,
      "continentalTitles": 0,
      "clubContinentalTitles": 0,
      "clubDomesticTitles": {"leagues": 0, "cups": 0}
    }
  },
  "teamInfo": null OR {
    "name": "Team name",
    "type": "club" OR "national",
    "fifaRanking": "Rank if national team",
    "achievementsSummary": {
      "worldCupTitles": 0,
      "continentalTitles": 0,
      "domesticTitles": {"leagues": 0, "cups": 0}
    }
  },
  "worldCupInfo": null OR {
    "year": 2026,
    "host": "Host countries"
  },
  "analysis": "Brief 50-word analysis",
  "videoSearchTerm": "Search term for highlights",
  "confidenceScore": 0.9
}

RULES:
1. If query is a player (like Messi, Ronaldo), fill playerInfo
2. If query is a club (like Real Madrid, Barcelona), fill teamInfo with type: "club"
3. If query is a country (like Spain, Brazil), fill teamInfo with type: "national"
4. If query is about World Cup, fill worldCupInfo
5. Only fill ONE of playerInfo, teamInfo, or worldCupInfo
6. Use accurate, real data
7. Return ONLY the JSON object

For "${query}":`;

  try {
    const completion = await groq.chat.completions.create({
      messages: [{ role: 'user', content: prompt }],
      model: 'llama-3.3-70b-versatile',
      temperature: 0.1,
      max_tokens: 1500,
    });

    const content = completion.choices[0]?.message?.content || '{}';
    console.log('📄 AI Response:', content.substring(0, 300));
    
    const parsed = safeParseJSON(content);
    console.log('✅ Parsed:', {
      hasPlayer: !!parsed.playerInfo,
      hasTeam: !!parsed.teamInfo,
      hasWorldCup: !!parsed.worldCupInfo,
      teamType: parsed.teamInfo?.type
    });
    
    return parsed;
    
  } catch (error) {
    console.error('Groq error:', error);
    return {
      playerInfo: null,
      teamInfo: null,
      worldCupInfo: null,
      analysis: "Temporary service issue",
      videoSearchTerm: "football",
      confidenceScore: 0.5
    };
  }
}

// YouTube search
async function searchYouTube(searchTerm: string) {
  try {
    const apiKey = process.env.YOUTUBE_API_KEY;
    
    if (!apiKey) {
      return getPublicYouTubeFallback(searchTerm);
    }

    const response = await axios.get('https://www.googleapis.com/youtube/v3/search', {
      params: {
        part: 'snippet',
        q: `${searchTerm} football highlights`,
        type: 'video',
        maxResults: 1,
        key: apiKey,
        videoEmbeddable: 'true',
        order: 'viewCount',
      },
      timeout: 5000,
    });

    if (response.data.items?.length > 0) {
      const videoId = response.data.items[0].id.videoId;
      return `https://www.youtube.com/embed/${videoId}`;
    }
    
    return getPublicYouTubeFallback(searchTerm);
  } catch (error) {
    return getPublicYouTubeFallback(searchTerm);
  }
}

function getPublicYouTubeFallback(searchTerm: string) {
  const term = searchTerm.toLowerCase();
  const videos: Record<string, string> = {
    'real madrid': 'XfyZ6EueJx8',
    'barcelona': '3X7XG5KZiUY',
    'messi': 'ZO0d8r_2qGI',
    'ronaldo': 'OUKGsb8CpF8',
    'world cup': 'dZqkf1ZnQh4',
  };

  for (const [key, videoId] of Object.entries(videos)) {
    if (term.includes(key)) {
      return `https://www.youtube.com/embed/${videoId}`;
    }
  }

  return 'https://www.youtube.com/embed/dZqkf1ZnQh4';
}

// Main API handler
export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader('Access-Control-Allow-Headers', 'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version');

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  const { action, query } = req.query;

  if (action === 'search' && query && typeof query === 'string') {
    console.log(`\n=== SEARCH: "${query}" ===`);
    
    try {
      const aiAnalysis = await analyzeFootballQuery(query);
      
      // Determine type
      let responseType = 'general';
      if (aiAnalysis.playerInfo) {
        responseType = 'player';
      } else if (aiAnalysis.teamInfo) {
        responseType = aiAnalysis.teamInfo.type === 'national' ? 'national' : 'club';
      } else if (aiAnalysis.worldCupInfo) {
        responseType = 'worldCup';
      }
      
      console.log('🎯 Type determined:', responseType);
      
      const youtubeUrl = await searchYouTube(aiAnalysis.videoSearchTerm || query);
      
      const response = {
        success: true,
        query: query,
        timestamp: new Date().toISOString(),
        type: responseType,
        data: aiAnalysis.playerInfo || aiAnalysis.teamInfo || aiAnalysis.worldCupInfo || null,
        playerInfo: aiAnalysis.playerInfo || null,
        teamInfo: aiAnalysis.teamInfo || null,
        worldCupInfo: aiAnalysis.worldCupInfo || null,
        youtubeUrl: youtubeUrl,
        analysis: aiAnalysis.analysis || `Analysis of ${query}`,
        confidence: aiAnalysis.confidenceScore || 0.8,
        source: 'Groq AI'
      };

      console.log('✅ Sending response with type:', responseType);
      return res.status(200).json(response);
      
    } catch (error) {
      console.error('API error:', error);
      
      return res.status(200).json({
        success: false,
        query: query,
        type: 'error',
        error: 'Service temporarily unavailable',
        timestamp: new Date().toISOString(),
        youtubeUrl: getPublicYouTubeFallback(query),
        analysis: `Please try again.`,
      });
    }
  }

  res.status(200).json({
    message: 'FutbolAI API',
    version: '1.0',
    endpoint: 'GET /api/ai?action=search&query=your-query'
  });
}